### ISSUE TITLE
讨论一下User表结构的设计

### ISSUE THREAD

**Issue by ZhaoQi99** [snnucs/ExpenseClaimAutomationSystem#5]
大家先找几个网上现成的报销系统看看吧～链接贴在下面～

**Comment by ZhaoQi99** [comment]
Lock by #9

**Comment by FengXiangrong** [comment]
http://e8.weaver.com.cn/wui/main.jsp

**Comment by ZhaoQi99** [comment]
Auth in Django:https://docs.graphene-python.org/projects/django/en/latest/authorization/#authorization-in-django

**Comment by ZhaoQi99** [comment]
看看除了这些字段，还要加什么嘛？

**Comment by ZhaoQi99** [comment]
> 看看除了这些字段，还要加什么嘛？ https://docs.djangoproject.com/en/2.2/topics/auth/default/#the-loginrequired-mixin
> @FengXiangrong @Icey116

我觉得还要加个头像

**Comment by ZhaoQi99** [comment]
https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#specifying-custom-user-model

**Comment by FengXiangrong** [comment]
所属单位？

**Comment by ZhaoQi99** [comment]
┗|｀O′|┛ 嗷~~~

**Comment by ZhaoQi99** [comment]
firest_name

> 所属单位？

┗|｀O′|┛ 嗷~~
first_name跟last_name啥的，冗余不....
我咋觉得自带的好多没用

**Comment by FengXiangrong** [comment]
> 
> 
> > 所属单位？
> 
> ┗|｀O′|┛ 嗷~~
> first_name跟last_name啥的，冗余不....
> 我咋觉得自带的好多没用

感觉好像有点冗余，我们就弄个姓名？感觉呢个偏英文习惯

![图片](https://user-images.githubusercontent.com/51938929/60592912-2de32800-9dd4-11e9-94e5-654db60fee6b.png)
如果是个单位话，我们导入单位数据库的接口好弄吗？

**Comment by ZhaoQi99** [comment]
哎呦，导入什么的先不管，最后一同处理，都是增删改查~问题不大~

**Comment by ZhaoQi99** [comment]
> > > 所属单位？
> > 
> > 
> > ┗|｀O′|┛ 嗷~~
> > first_name跟last_name啥的，冗余不....
> > 我咋觉得自带的好多没用
> 
> 感觉好像有点冗余，我们就弄个姓名？感觉呢个偏英文习惯
> 
> ![图片](https://user-images.githubusercontent.com/51938929/60592912-2de32800-9dd4-11e9-94e5-654db60fee6b.png)
> 如果是个单位话，我们导入单位数据库的接口好弄吗？

哎呦，导入什么的先不管，最后一同处理，都是增删改查问题不大

**Comment by FengXiangrong** [comment]
> 
> 
> > > > 所属单位？
> > > 
> > > 
> > > ┗|｀O′|┛ 嗷~~
> > > first_name跟last_name啥的，冗余不....
> > > 我咋觉得自带的好多没用
> > 
> > 
> > 感觉好像有点冗余，我们就弄个姓名？感觉呢个偏英文习惯
> > ![图片](https://user-images.githubusercontent.com/51938929/60592912-2de32800-9dd4-11e9-94e5-654db60fee6b.png)
> > 如果是个单位话，我们导入单位数据库的接口好弄吗？
> 
> 哎呦，导入什么的先不管，最后一同处理，都是增删改查问题不大

好的

**Comment by ZhaoQi99** [comment]
> > > 所属单位？
> > 
> > 
> > ┗|｀O′|┛ 嗷~~
> > first_name跟last_name啥的，冗余不....
> > 我咋觉得自带的好多没用
> 
> 感觉好像有点冗余，我们就弄个姓名？感觉呢个偏英文习惯
> 
> ![图片](https://user-images.githubusercontent.com/51938929/60592912-2de32800-9dd4-11e9-94e5-654db60fee6b.png)
> 如果是个单位话，我们导入单位数据库的接口好弄吗？

研究了一下，还是扩展自带的那个吧，原因有三:
- 前端到时候可能有修改:姓/名的需求，得分开存姓与名
- 自带的User中有group，便于分组的管理
- 不从自带的User扩展的话，得继承自[ AbstractBaseUser](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#specifying-a-custom-user-model),有点麻烦....

**Comment by FengXiangrong** [comment]
> 
> 
> > > > 所属单位？
> > > 
> > > 
> > > ┗|｀O′|┛ 嗷~~
> > > first_name跟last_name啥的，冗余不....
> > > 我咋觉得自带的好多没用
> > 
> > 
> > 感觉好像有点冗余，我们就弄个姓名？感觉呢个偏英文习惯
> > ![图片](https://user-images.githubusercontent.com/51938929/60592912-2de32800-9dd4-11e9-94e5-654db60fee6b.png)
> > 如果是个单位话，我们导入单位数据库的接口好弄吗？
> 
> 研究了一下，还是扩展自带的那个吧，原因有三:
> 
>     * 前端到时候可能有修改:姓/名的需求，得分开存姓与名
> 
>     * 自带的User中有group，便于分组的管理
> 
>     * 不从自带的User扩展的话，得继承自[ AbstractBaseUser](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#specifying-a-custom-user-model),有点麻烦....

木有问题，那就用自带的叭
