### ISSUE TITLE
主界面加一个footer吧

### ISSUE THREAD

**Issue by ZhaoQi99** [snnucs/ExpenseClaimAutomationSystem#67]
- https://vuetifyjs.com/zh-Hans/components/application
- https://vuetifyjs.com/zh-Hans/components/footer

**Comment by ZhaoQi99** [comment]
#66  就是加了个工具条

**Comment by ZhaoQi99** [comment]
先做这个吧,然后在写404那个 @cylhappy

**Comment by ZhaoQi99** [comment]
写在`components`里面

**Comment by Icey116** [comment]
over~Yeah~

**Comment by ZhaoQi99** [comment]
> over,Yeah

Good job!
