### ISSUE TITLE
对校内现有报销系统的具体流程进行调研

### ISSUE THREAD

**Issue by ZhaoQi99** [snnucs/ExpenseClaimAutomationSystem#9]
链接http://ssocaiwu.snnu.edu.cn:8080/Newindex.aspx

**Comment by Icey116** [comment]
调研结束~

**Comment by ZhaoQi99** [comment]
> 调研结束~

把相关文档传上来把，顺便熟悉一下流程~
- `git checkout -b xxx origin/master`新建一条分支(注意分支命名规范)
- 项目根目录下新建一个文件夹docs/xx/(docs文件夹下的xx文件夹)
- 相关文件移动至xx文件夹中
- `git add .`
- `git commit -m "xxx"`
- `git push origin`（应该会报错，按照提示的来）

**Comment by Icey116** [comment]
> > 调研结束~
> 
> 把相关文档传上来把，顺便熟悉一下流程~
> 
> * `git checkout -b xxx origin/master`新建一条分支(注意分支命名规范)
> * 项目根目录下新建一个文件夹docs/xx/(docs文件夹下的xx文件夹)
> * 相关文件移动至xx文件夹中
> * `git add .`
> * `git commit -m "xxx"`
> * `git push origin`（应该会报错，按照提示的来）
> * Github上提一个pr

好的~

**Comment by ZhaoQi99** [comment]
嗯~ o(*￣▽￣*)o？文档呢
@Icey116

**Comment by ZhaoQi99** [comment]
@cylhappy hi，文档还能找到嘛~

**Comment by cylhappy** [comment]
在的

**Comment by ZhaoQi99** [comment]
> 在的

那有空的话，给他整上来....
放在根目录的`docs`文件夹下....

**Comment by cylhappy** [comment]
我进行了一波操作，不知道传上去了没

**Comment by ZhaoQi99** [comment]
> 我进行了一波操作，不知道传上去了没

咋费事~

**Comment by cylhappy** [comment]
看一下我传上去了吗
@ZhaoQi99

**Comment by cylhappy** [comment]
感觉成功了的感觉

**Comment by ZhaoQi99** [comment]
> 感觉成功了的感觉

Good，上去了~再去提个pull request试试~

**Comment by ZhaoQi99** [comment]
https://github.com/snnucs/ExpenseClaimAutomationSystem/compare/master...feature/9/add-diaoyan

在这提呢~
@cylhappy

**Comment by cylhappy** [comment]
稍等

**Comment by cylhappy** [comment]
对着吗，是不是错了
